### ISSUE TITLE
exec /entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by icetu0228** [onejar99/gitbook-build-publish-action#4] opened 2023-08-03 08:18 UTC
Hi,

最近執行都會出現下面錯誤而無法正常build and deploy
請問是設定問題嗎?

exec /entrypoint.sh: no such file or directory

**Comment by onejar99** [comment] 2023-08-03 15:16
## [situation]
* reproducible: yes
* log: https://github.com/onejar99/demo-build-and-publish-gitbook/actions/runs/5751697570/job/15591042019
* failed step: Build and deploy
```
Run onejar99/gitbook-build-publish-action@v1.0.2
  env:
    MY_SECRET: ***
    USER_NAME: onejar99
    USER_EMAIL: onejar99@gmail.com
    BOOK_DIR: book_sources
/usr/bin/docker run --name bedb41e2cecc2ab4e4379a1bc1491ff781c7b_7fe249 --label 5bedb4 --workdir /github/workspace --rm -e "MY_SECRET" -e "USER_NAME" -e "USER_EMAIL" -e "BOOK_DIR" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/demo-build-and-publish-gitbook/demo-build-and-publish-gitbook":"/github/workspace" 5bedb4:1e2cecc2ab4e4379a1bc1491ff781c7b
exec /entrypoint.sh: no such file or directory
```

## [root cause]
The based image in dockerfile of this GitHub Action was using `onejar99/gitbook:light`. Recently, I made a more lightweight version for `light` tag by alpine. That caused this GitHub Action pulled the new version image but it's not compatible.

https://github.com/onejar99/docker-personal-images/commit/80bc72e2a6d9be2faedd7778147bd262111bf70b#diff-5eac759faa71982e306680a632edc416436cb272432e8e2220dc0519a59e1f0c


## [solution]
Force specify based image tag with fixed version instead of alias tag.

## [release]
Released with **v1.0.3** and verified.
https://github.com/onejar99/demo-build-and-publish-gitbook/actions/runs/5752400097

**Comment by onejar99** [comment] 2023-08-03 15:21
@icetu0228 謝謝你的回報。

這個 GitHub Action 使用了我另一個 image 作為 based image，剛好我最近對那個 based image 做改版，沒注意到這個 GitHub Action 會去拉到新版 image 而且不相容，導致執行錯誤。 

已經修復一版 v1.0.3，歡迎升級試試看。

**Comment by icetu0228** [comment] 2023-08-04 07:37
感謝 @onejar99 
v1.0.3可以正常執行了

**Closed as completed** 2023-08-04 07:37 UTC
